[project]
name = "live-transcribe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "realtimestt>=0.3.104",
    "pyaudio>=0.2.11",
    "rich>=14.1.0",
    "pyautogui>=0.9.54",
]
